site_name: Event Storming
repo_url: https://github.com/phftavares/doc-event-storming
repo_name: phftavares/event-storming
theme:
  name: material
  features:
    - navigation.sections
plugins:
  - git-revision-date
markdown_extensions:
  - meta
  